# Generated by Django 3.1.3 on 2020-11-30 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20201128_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
